#!/bin/bash

# Quick Deploy Commands for SoloMemo
# Save this file for quick reference

echo "=========================================="
echo "SoloMemo Quick Deploy Reference"
echo "=========================================="
echo ""
echo "🌐 Domain: solo.pontium.org"
echo "🖥️  Server: ubuntu@mypetpaw.net"
echo "📁 Directory: /home/ubuntu/SoloMemo"
echo ""
echo "=========================================="
echo "QUICK COMMANDS"
echo "=========================================="
echo ""
echo "1️⃣  SSH Connect:"
echo "   ssh ubuntu@mypetpaw.net"
echo ""
echo "2️⃣  Initial Deploy:"
echo "   cd ~"
echo "   git clone <repo-url> SoloMemo"
echo "   cd SoloMemo"
echo "   chmod +x deploy.sh"
echo "   ./deploy.sh"
echo ""
echo "3️⃣  Update (after code changes):"
echo "   cd ~/SoloMemo"
echo "   ./update.sh"
echo ""
echo "4️⃣  View Logs:"
echo "   cd ~/SoloMemo"
echo "   docker-compose -f docker-compose.prod.yml logs -f"
echo ""
echo "5️⃣  Restart Containers:"
echo "   cd ~/SoloMemo"
echo "   docker-compose -f docker-compose.prod.yml restart"
echo ""
echo "6️⃣  Stop All:"
echo "   cd ~/SoloMemo"
echo "   docker-compose -f docker-compose.prod.yml down"
echo ""
echo "7️⃣  Manual Backup:"
echo "   /usr/local/bin/solomemo-backup.sh"
echo ""
echo "8️⃣  SSL Certificate Renewal:"
echo "   sudo certbot renew"
echo ""
echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "❌ 502 Bad Gateway:"
echo "   docker-compose -f docker-compose.prod.yml restart app"
echo "   sudo systemctl restart nginx"
echo ""
echo "❌ Database Error:"
echo "   docker-compose -f docker-compose.prod.yml restart db"
echo "   docker-compose -f docker-compose.prod.yml logs db"
echo ""
echo "❌ Clear All Caches:"
echo "   docker-compose -f docker-compose.prod.yml exec app php artisan cache:clear"
echo "   docker-compose -f docker-compose.prod.yml exec app php artisan config:clear"
echo "   docker-compose -f docker-compose.prod.yml exec app php artisan route:clear"
echo ""
echo "=========================================="
echo "IMPORTANT FILES"
echo "=========================================="
echo ""
echo "📄 Environment: ~/SoloMemo/backend/.env"
echo "📄 Nginx Config: /etc/nginx/sites-available/solo.pontium.org"
echo "📄 SSL Cert: /etc/letsencrypt/live/solo.pontium.org/"
echo "📄 Backup Script: /usr/local/bin/solomemo-backup.sh"
echo ""
echo "=========================================="
